namespace: ravi-ml-2june

#Note: A namespace with many characters will cause storage
account creation to fail due to storage account names having a limit of 24 charac‐
ters.
 postfix: ao04
 location: eastus

 environment: prod
 enable_aml_computecluster: true
 enable_aml_secure_workspace: true
 enable_monitoring: false
